# -*- coding: utf-8 -*-
"""StreamlitDeployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NVK-dqvcgG9C4p-0XNzK2YdQGloB_ye
"""

import numpy as np
import pandas as pd
import streamlit as st
from sklearn import preprocessing
import pickle

model = pickle.load(open('svmmodel.pkl', 'rb'))
cols=['loan_amount','property_value','interest_rate','term','income']

def main():
    st.title("Loan Default Predictor")
    html_temp = """
    <div style="background:#025246 ;padding:10px">
    <h2 style="color:white;text-align:center;">Loan Default Prediction App </h2>
    </div>
    """
    st.markdown(html_temp, unsafe_allow_html = True)


    loan_amount = st.text_input("Loan Amount","0")
    property_value = st.text_input("Property Value","0")
    interest_rate = st.text_input("Interest Rate","0")
    term = st.text_input("Term","0")
    income = st.text_input("Income","0")

    if st.button("Predict"):
        features = ['loan_limit_cf', 'loan_limit_missing', 'loan_limit_ncf',
       'Gender_Female', 'Gender_Joint', 'Gender_Male',
       'Gender_Sex Not Available', 'approv_in_adv_missing',
       'approv_in_adv_nopre', 'approv_in_adv_pre', 'total_units_1U',
       'total_units_3U', 'total_units_4U', 'loan_purpose_p1',
       'loan_purpose_p3', 'Credit_Worthiness_l1', 'Credit_Worthiness_l2',
       'Neg_ammortization_missing',
       'Neg_ammortization_neg_amm', 'Neg_ammortization_not_neg',
       'interest_only_not_int', 'lump_sum_payment_lpsm',
       'construction_type_sb', 'occupancy_type_ir', 'occupancy_type_sr',
       'Secured_by_home', 'Secured_by_land', 'credit_type_CIB',
       'credit_type_CRIF', 'credit_type_EQUI', 'credit_type_EXP',
       'co-applicant_credit_type_CIB', 'co-applicant_credit_type_EXP',
       'submission_of_application_missing',
       'submission_of_application_to_inst', 'Region_North',
       'Region_North-East', 'Region_south', 'Security_Type_Indirect',
       'Security_Type_direct', 'loan_amount', 'rate_of_interest',
       'Upfront_charges', 'term', 'property_value', 'income', 'Credit_Score',
       'LTV', 'dtir1', 'age_encoded', 'loan_type_encoded']

        data = {'loan_limit_cf': -1.468563640679615,
                'loan_limit_missing': 1.9537079229283951,
                'loan_limit_ncf': 2.308099162582358,
                'Gender_Female': -0.25043398789886645,
                'Gender_Joint': 0.42789676960024714,
                'Gender_Male': -0.6687135673516199,
                'Gender_Sex Not Available': -0.8170281565727876,
                'approv_in_adv_missing': 1.4872114847802707,
                'approv_in_adv_nopre': -1.0414385241258308,
                'approv_in_adv_pre': -0.3969325240168114,
                'total_units_1U': 1.0,
                'total_units_3U': 0.0,
                'total_units_4U': 0.0,
                'loan_purpose_p1': 0.0,
                'loan_purpose_p3': 0.0,
                'Credit_Worthiness_l1': 1.0,
                'Credit_Worthiness_l2': 1.0,
                'Neg_ammortization_missing': 0.0,
                'Neg_ammortization_neg_amm': 0.0,
                'Neg_ammortization_not_neg': 1.0,
                'interest_only_not_int': 1.0,
                'lump_sum_payment_lpsm': 0.0,
                'construction_type_sb': 0.0,
                'occupancy_type_ir': 1.0,
                'occupancy_type_sr': 0.0,
                'Secured_by_home': 1.0,
                'Secured_by_land': 0.0,
                'credit_type_CIB': 1.0,
                'credit_type_CRIF': 0.0,
                'credit_type_EQUI': 1.0,
                'credit_type_EXP': 0.0,
                'co-applicant_credit_type_CIB': 1.0,
                'co-applicant_credit_type_EXP': 0.0,
                'submission_of_application_missing': 1.0,
                'submission_of_application_to_inst': 1.0,
                'Region_North': 0.0,
                'Region_North-East': 1.0,
                'Region_south': 0.0,
                'Security_Type_Indirect': 0.0,
                'Security_Type_direct': 0.0,
                'loan_amount': loan_amount,
                'rate_of_interest': interest_rate,
                'Upfront_charges': 1.0,
                'term': term,
                'property_value': property_value,
                'income': income,
                'Credit_Score': 1.0,
                'LTV': 0.0,
                'dtir1': 1.0,
                'age_encoded': 4.0,
                'loan_type_encoded': 0.0}
        print(data)

        data2={'loan_limit_cf': -1.014054581862527,
        'loan_limit_missing': -0.00882170656121059,
        'loan_limit_ncf': -0.025756739733656497,
        'Gender_Female': 0.010257451743343124,
        'Gender_Joint': 0.42789676960024714,
        'Gender_Male': -1.2908379090010345,
        'Gender_Sex Not Available': -0.34326041060358403,
        'approv_in_adv_missing': 0.20990271710822242,
        'approv_in_adv_nopre': 0.44034971032970893,
        'approv_in_adv_pre': -0.1883332142827212,
        'total_units_1U': 1.0,
        'total_units_3U': 0.0,
        'total_units_4U': 0.0,
        'loan_purpose_p1': 0.0,
        'loan_purpose_p3': 0.0,
        'Credit_Worthiness_l1': 0.0,
        'Credit_Worthiness_l2': 1.0,
        'Neg_ammortization_missing': 1.0,
        'Neg_ammortization_neg_amm': 0.0,
        'Neg_ammortization_not_neg': 0.0,
        'interest_only_not_int': 1.0,
        'lump_sum_payment_lpsm': 0.0,
        'construction_type_sb': 0.0,
        'occupancy_type_ir': 1.0,
        'occupancy_type_sr': 0.0,
        'Secured_by_home': 1.0,
        'Secured_by_land': 1.0,
        'credit_type_CIB': 0.0,
        'credit_type_CRIF': 0.0,
        'credit_type_EQUI': 1.0,
        'credit_type_EXP': 0.0,
        'co-applicant_credit_type_CIB': 1.0,
        'co-applicant_credit_type_EXP': 0.0,
        'submission_of_application_missing': 0.0,
        'submission_of_application_to_inst': 1.0,
        'Region_North': 0.0,
        'Region_North-East': 0.0,
        'Region_south': 0.0,
        'Security_Type_Indirect': 0.0,
        'Security_Type_direct': 1.0,
        'loan_amount': 0.0,
        'rate_of_interest': 0.0,
        'Upfront_charges': 1.0,
        'term': 0.0,
        'property_value': 0.0,
        'income': 0.0,
        'Credit_Score': 1.0,
        'LTV': 0.0,
        'dtir1': 1.0,
        'age_encoded': 3.0,
        'loan_type_encoded': 0.0}
        df=pd.DataFrame([list(data2.values())], columns=features)

        print(df)
        features_list = df.values.tolist()
        prediction = model.predict(features_list)

        output = int(prediction[0])
        if output == 1:
            text = "Default"
        else:
            text = "No-Default"

        st.success('Borrower Loan will {}'.format(text))

if __name__=='__main__':
    main()